# Generated by Django 3.2.24 on 2024-07-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
                ('author', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
